### ISSUE TITLE
Just displays a sample chat.

### ISSUE THREAD

**Issue by numboDumbo** [srilakshmikanthanp/chatviewer#21]
Upon importing the chat, the UI only shows a sample chat.

Cool project BTW. Keep It UP!.

**Comment by srilakshmikanthanp** [comment]
Thanks for raising the issue can you provide more info, Like A Sample Chat and procedure to reproduce Issue?

**Comment by srilakshmikanthanp** [comment]
Since this issue got no response for some time I am closing this as not planned, if you face any problems please reopen it with additional information.
