### ISSUE TITLE
MP4 video attachments are not attached

### ISSUE THREAD

**Issue by usbv90** [srilakshmikanthanp/chatviewer#24]
MP4 video attachments are not attached, otherwise, it works great.

**Comment by srilakshmikanthanp** [comment]
Thanks for raising an issue, can you able to provide any additional info like an example chat that reproduces the issue?

**Comment by srilakshmikanthanp** [comment]
Fixed with 19a7403a1f250225ec1f13fbd5fc377b68546ae9, Let me know if You face any problems :)
