### ISSUE TITLE
Invalid Nx Cloud access token

### ISSUE THREAD

**Issue by tayomoore** [srilakshmikanthanp/chatviewer#25]
When I run `npx nx serve web` I get an error:
```
 >  NX   Nx Cloud Problems

   - Invalid Nx Cloud access token. Token: M2M2Y2VkZmMtODE0YS00M2FiLWExOGItNTM5ODU4MzczZGM2fHJlYWQtd3JpdGU=
```

Does it need to use nx cloud? Can it just be run locally?

**Comment by srilakshmikanthanp** [comment]
I have completely removed Nx Cloud from the project. Please try again and let me know the results. Thanks! :)

**Comment by srilakshmikanthanp** [comment]
I am closing this as completed if you have any issues please reopen the same, Thanks :)
